add option for coupling LDAS with ADAS 	modified:   src/Applications/GEOSdas_App/GEOSdas.csm 	modified:   src/Applications/GEOSdas_App/fvpsas 	modified:   src/Applications/GEOSdas_App/fvsetup 	modified:   src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/atm_ens.j 	new file:   src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/atmos_eldas.csh 	modified:   src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/AGCM.rc.tmpl 	modified:   src/Applications/NCEP_Etc/NCEP_enkf/scripts/gmao/etc/HISTAENS.rc.tmpl

diff --git a/src/Applications/GEOSdas_App/fvpsas b/src/Applications/GEOSdas_App/fvpsas
--- a/src/Applications/GEOSdas_App/fvpsas
+++ b/src/Applications/GEOSdas_App/fvpsas
@@ -112,6 +112,7 @@
 #  30May2013 Todling    Add GetAODinfo4Fcst_ to retrieve AOD fields for fcsts
 #  13Jun2020 Todling    Time aerosol analysis
 #  19Oct2020 Todling    Call to JEDI analysis
+#  10Mar2021 sqzhang    Add call to LandAnalysis when coupling 
 #
 #-----------------------------------------------------------------------------
 
@@ -416,6 +417,21 @@
 
          endif
 
+## sqz--merge---start  ldas-coupling  
+#        Run Land analysis
+#        -----------------
+
+         if ( $LDAS_ANA ) then
+            echo "  LDAS coupling: fvpsas LDAS_ANA  run lenkf "
+
+                                                       zeit_ci.x LandAnalysisRun
+              Call LandAnalysisRun_()
+                                                       zeit_co.x LandAnalysisRun
+         endif
+
+##----------sqz-merge---end 
+
+
 #        Run the analysis if not doing replay
 #        -----------------------------------
          if ( ! -e replay.acq ) then
@@ -473,6 +489,38 @@
                 endif
             endif
          endif
+
+# sqz-merge---start for ldas-coupling  
+#        Wait here for Land analysis if it is being fed back to GCM
+#        ------------------------------------------------------------- 
+
+       if ( ( $LDAS_ANA ) && ( $LDASFDBK ) ) then
+        echo " LDAS coupling:fvpsas job status and Increments files "
+
+               if ($?ldasJobIDs) then
+                    $FVROOT/bin/jobIDfilter -w $ldasJobIDs
+                    unsetenv ldasJobIDs
+                endif
+          set lenkf_status_file = ${FVHOME}/lana/lenkf_job_completed.txt
+               rm -f $lenkf_status_file
+               cp $LDHOME/run/lenkf_job_completed.txt  $lenkf_status_file
+
+               set lenkf_status = `cat $lenkf_status_file`
+               echo $lenkf_status
+               echo  $lenkf_status ": lenkf_status"
+              if ($lenkf_status =~  SUCCEEDED )  then
+
+               echo "LDAS coupling fvpsas Lenkf job SUCCEEDED, stageLdasIncr"
+                                                      zeit_ci.x StageLdasIncr
+                 Call StageLdasIncr_()
+                                                      zeit_co.x StageLdasIncr
+              else
+                 echo "LDAS coupling fvpsas  Lenkf job failed"
+                 exit 90
+
+              endif
+        endif
+#--sqz-merge--end 
 
 #        Convert analysis eta file into GCM restart
 #        ------------------------------------------
